### ISSUE TITLE
[feature] dont toggle the sidebar if its hidden.

### ISSUE THREAD

**Issue by ctf0** [dreki/vscode-auto-close-folders#1]
is it possible ?

**Comment by dreki** [comment]
@ctf0 I tried many ways to get this to work. That was the original intention of this extension. There are one or two very annoying ways to 'simulate' it, but they have their own issues. Hopefully one day VS Code will make it possible.

Thank you for your interest in the extension. Sorry for the extended delay in my response.

**Comment by ctf0** [comment]
oh hi, np, anyway there is a way around to get it to work and it goes like this

1. create 2 commands with when `sideBarVisible` & `!sideBarVisible`
2. inside the extension, run the commands with `vscode.commands.executeCommand`
3. win 🚀

**Comment by dreki** [comment]
@ctf0, thank you for the help. I tried that out and it didn't work. VS Code will hide the command from the command palette, but it can still be executed by code.

So, there's just no way for an extension to dynamically tell if the sidebar or explorer are currently visible. It's very frustrating.
